# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('kd_bahan', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=25)),
                ('netto', models.DecimalField(blank=True, decimal_places=2, help_text='dalam gram', max_digits=9, null=True)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('kd_item', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=25)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('bahan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produk.Bahan')),
                ('jumlah', models.DecimalField(blank=True, decimal_places=2, help_text='jumlah pemakaian dalam gram', max_digits=9, null=True)),
            ],
            bases=('produk.bahan',),
        ),
        migrations.AddField(
            model_name='bahan',
            name='item',
            field=models.ManyToManyField(to='produk.Item'),
        ),
    ]
