# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan',
            name='kd_bahan',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='kd_item',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
