# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='bahan',
            name='item',
        ),
        migrations.AddField(
            model_name='bahan',
            name='item',
            field=models.ManyToManyField(to='produk.Item'),
        ),
        migrations.AlterField(
            model_name='bahan',
            name='kd_bahan',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formula',
            name='jumlah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='dalam gram', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='kd_item',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
