# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20170511_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahan',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='dalam gram', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='jumlah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='jumlah pemakaian dalam gram', max_digits=9, null=True),
        ),
    ]
