# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20170417_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='item',
        ),
        migrations.AddField(
            model_name='bahan',
            name='item',
            field=models.ManyToManyField(to='produk.Item'),
        ),
    ]
