# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_auto_20170512_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bahan',
            old_name='neto',
            new_name='netto',
        ),
    ]
