# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_auto_20170529_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='harga',
        ),
    ]
