# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_auto_20170503_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bahan',
        ),
        migrations.AlterField(
            model_name='bahan',
            name='item',
            field=models.ManyToManyField(to='produk.Item'),
        ),
    ]
