# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_remove_bahan_harga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bahan',
            options={'ordering': ['nama']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nama']},
        ),
    ]
