# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_auto_20170503_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='harga',
        ),
        migrations.AlterField(
            model_name='formula',
            name='jumlah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='dalam gram', max_digits=9),
        ),
    ]
