# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('jumlah', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('jumlah', models.IntegerField(default=1)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Bahan')),
            ],
        ),
        migrations.CreateModel(
            name='Rekap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('tot_masuk', models.DecimalField(decimal_places=2, help_text='Total Pemasukan', max_digits=9)),
                ('tot_keluar', models.DecimalField(decimal_places=2, help_text='Total Pengeluaran', max_digits=9)),
                ('pemasukan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pemasukan')),
                ('pengeluaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pengeluaran')),
            ],
        ),
    ]
