# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalAwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('kd_masuk', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('jumlah', models.IntegerField(default=1)),
                ('keterangan', models.CharField(max_length=50)),
                ('total_harga', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Item')),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('kd_keluar', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('harga', models.IntegerField()),
                ('keterangan', models.CharField(blank=True, help_text='jika pembelian tidak ada di kolom bahan', max_length=75)),
                ('jumlah', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Bahan')),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Rekap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('tot_masuk', models.DecimalField(decimal_places=2, help_text='Total Pemasukan', max_digits=9)),
                ('tot_keluar', models.DecimalField(decimal_places=2, help_text='Total Pengeluaran', max_digits=9)),
                ('pemasukan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pemasukan')),
                ('pengeluaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pengeluaran')),
            ],
        ),
    ]
