# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateField(blank=True, null=True, verbose_name='timestamp')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pemasukan',
            options={'ordering': ['tanggal']},
        ),
        migrations.RenameField(
            model_name='pengeluaran',
            old_name='bahan',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='pemasukan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pengeluaran',
            name='id',
        ),
        migrations.AddField(
            model_name='pemasukan',
            name='kd_masuk',
            field=models.CharField(default=0, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pemasukan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='kd_keluar',
            field=models.CharField(default=1, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='keterangan',
            field=models.CharField(blank=True, help_text='jika pembelian tidak ada di kolom bahan', max_length=75),
        ),
    ]
