# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemasukan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pengeluaran',
            name='id',
        ),
        migrations.AddField(
            model_name='pemasukan',
            name='kd_masuk',
            field=models.CharField(default=1, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='kd_keluar',
            field=models.CharField(default=1, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
