# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170511_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
