# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170424_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='keterangan',
            field=models.CharField(default='', help_text='jika pembelian tidak ada di kolom bahan', max_length=75),
            preserve_default=False,
        ),
    ]
