# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemasukan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9),
        ),
    ]
