# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_pengeluaran_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
