# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170506_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengeluaran',
            old_name='bahan',
            new_name='item',
        ),
    ]
