# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170512_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemasukan',
            name='total_harga',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
