# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170507_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengeluaran',
            name='keterangan',
            field=models.CharField(blank=True, help_text='jika pembelian tidak ada di kolom bahan', max_length=75),
        ),
    ]
