# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20170513_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemasukan',
            name='total_harga',
            field=models.IntegerField(default=0),
        ),
    ]
