# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170513_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={'ordering': ['tanggal']},
        ),
    ]
