# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('f', 'Founder'), ('p', 'Pegawai')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('alamat', models.CharField(blank=True, max_length=30)),
                ('tgl_lahir', models.DateField(default=datetime.date(1992, 1, 1))),
            ],
        ),
    ]
