# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_user',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
    ]
